tg_bot_token: YOUR_TELEGRAM_BOT_TOKEN
tg_chat_id: YOUR_TRADE_CHAT_ID
tg_alert_chat_id: YOUR_ALERT_CHAT_ID
pocker_api_url: https://api.pockeruniverse.com/v1/fakevolume

files:
  coin_blacklist: blacklists/coins.txt
  dev_blacklist: blacklists/devs.txt

filters:
  min_liquidity: 10000
  min_volume: 50000
  max_age: 3600  # 1 hour in seconds